apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
resources:
  - cert-manager
  - plex
  - radarr
#  - prowlarr
  - qbittorrent
  - sonarr
  - homebridge
  - homeassistant
  - jackett
  - flaresolverr
  - bazarr
  - prometheus
  - blackbox-exporter
  - n8n
  - nextcloud
  - postgres
  - timemachine
  - homarr